config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/set_new_password/:confirmation_token' => 'staticpages#set_new_password', as: 'set_new_password'
  post 'staticpages/public_password_submit' => 'staticpages#public_password_submit', as: 'public_password_submit'
  get 'staticpages/public_password_reset' => 'staticpages#public_password_reset', as: 'public_password_reset'
  get 'users/:user_id/reset_password' => 'users#reset_password', as: 'reset_password'

  resources :books do
    collection do
      get 'search'
      get 'quick_loan'
      get 'list_by_category'
    end
  end
  

  resource :session, controller: "clearance/sessions", only: [:create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  
  resources :users do
    collection do
      get 'search'
    end
  end

  post '/books/quick_create', to: 'books#quick_create', as: 'quick_create_book'

  resources :loans 
  resources :categories
  resources :publishers 
  
  match '/users/:user_id/print_member_info', to: "users#print_member_info", via: 'post', as: 'print_member_info'
  match '/history/loans', to: "loans#history", via: 'get', as: 'loan_history'
  match '/loans/search_book', to: "loans#search_book", via: 'post', as: 'search_book'
  match '/loans/:id/book_return', to: "loans#book_return", via: 'get', as: 'book_return'
  match '/loans/:id/return_date_extend', to: "loans#return_date_extend", via: 'get', as: 'return_date_extend'
  match '/search', to: "staticpages#search", via: 'post'
  match '/staticpages/print_book_barcodes', to: "staticpages#print_book_barcodes", via: 'post', as: 'print_barcode'
  match '/staticpages/print_book_barcodes', to: "staticpages#print_book_barcodes", via: 'get'
  match '/staticpages/print_member_cards', to: "staticpages#print_member_cards", via: 'post', as: 'print_member'
  match '/staticpages/print_member_cards', to: "staticpages#print_member_cards", via: 'get'
  match '/staticpages/import_books', to: "staticpages#import_books", via: 'post', as: 'import_books'  
  match '/staticpages/import_members', to: "staticpages#import_members", via: 'post', as: 'import_members' 
  match '/staticpages/training', to: "staticpages#training", via: 'get', as: 'training' 
  root 'staticpages#home'

  get 'staticpages/help' => 'staticpages#help', as: 'help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

has_many :books, through: :loans
has_many :loans, dependent: :destroy

validates :member_id, uniqueness: :true, unless: :is_pending?
validates :ic, presence: :true, format: { with: /\d{6}\-\d{2}\-\d{4}/,
    message: "Invalid IC format" }


after_create :capitalize_name, :fill_up_birthday, :fill_up_gender

	def is_pending?
		self.member_id == 'Pending'
	end

	def member_id_pending
		self.update(member_id: 'Pending')
	end

	def read_count
		self.loans.all.count
	end

	def self.search(params)
		where("name like ? or email like ? or chinese_name like ? or phone like ? or ic like ? or member_id like ?", "%#{params[:search_term].upcase}%", "%#{params[:search_term]}%", "%#{params[:search_term]}%", "%#{params[:search_term]}%", "%#{params[:search_term]}%", "%#{params[:search_term]}%")
	end

	def capitalize_name
		self.update(name: name.upcase )
		if self.member_id == nil
		self.update(member_id: 'Pending')
		end
		return
	end

	def full_address
		self.line1 + self.line2 + " " + self.postcode + " " + self.city + " " + self.state
	end

  def email_optional?
    true
  end

  def fill_up_birthday
				a = self	
			  		unless a.ic.empty?
			  			b = a.ic[0...6].scan(/../)
							if b[0] > "17"
								b[0] = "19" + b[0]
							else 
								b[0] = "20" + b[0]
							end
							year = b[0]
							month = b[1]
							day = b[2]
							unless day > "31"
							a.update(birthday: Date.new(year.to_i, month.to_i, day.to_i))
							end
						end
  end

  def fill_up_gender
  	a = self
  		unless a.ic.empty?
  			b = a.ic
  			if b[13].to_i.odd?
  			a.update(gender: 'Male')
  			else
  			a.update(gender: 'Female')
  			end 
  		end
  end

	def is_admin?
		if self.user_type == 'admin'
			return true
		else
			return false
		end
	end


end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in? and !current_user.is_admin?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    # email = user_params.delete(:email)
    # password = user_params.delete(:password)
    # name = user_params.delete(:name)
    # ic = user_params.delete(:ic)
    # member_id = user_params.delete(:member_id)
    # phone = user_params.delete(:phone)
    # birthday = user_params.delete(:birthday)


    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = user_params[:email]
      user.password = user_params[:password]
      user.name = user_params[:name]
      user.ic = user_params[:ic]
      user.member_id = user_params[:member_id]
      user.phone = user_params[:phone]
      user.birthday = user_params[:birthday]
      user.line1 = user_params[:line1]
      user.line2 = user_params[:line2]
      user.line3 = user_params[:line3]
      user.postcode = user_params[:postcode]
      user.city = user_params[:city]
      user.state = user_params[:state]

    end
  end

  def user_params
    if params[Clearance.configuration.user_parameter].nil?
     Hash.new
    else
    # params[Clearance.configuration.user_parameter]
    params.require(:user).permit(:name, :ic, :phone, :email, :birthday, :member_id, :password, :user_type, :chinese_name, :line1, :line2, :line3, :postcode, :city, :state, :member_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  skip_before_action :require_login, only: [:update, :create]
  # GET /users
  # GET /users.json
  def index
    if params[:sort_by].nil?
       sort = "member_id desc"
    elsif params[:sort_by]=="member_id"
      sort = "member_id "+ params[:order]
    elsif params[:sort_by]=="name"
      sort = "name "+ params[:order]  
    end 

    if !current_user.is_admin?
    @users = User.where(id: current_user.id)
    else
    @users = User.all.order(sort).paginate(:page => params[:page], :per_page => 15)
    end
  end


  def new
    @user = User.new

  end


  # GET /users/1
  # GET /users/1.json
  def show

    @loans = @user.loans.where(has_returned: false).order("return_date ASC" )
    @loans_returned = @user.loans.where(has_returned: true)

  end


  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    params.permit(:reset)
    if params[:reset] == "true"
        if params[:user][:password] != params[:password] 
          redirect_to :back, alert: 'Password does not match.' 
        else
          respond_to do |format|
            if @user.update(user_params)
              format.html { redirect_to root_path, notice: 'User was successfully updated.' }
              format.json { render :show, status: :ok, location: @user }
            else
              format.html { redirect_to :back, alert:'Not processed, please try again.' }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
          end
        end      
    else
        if params[:user][:password] != params[:password] 
          redirect_to @user, alert: 'Password does not match.' 
        else
          respond_to do |format|
            if @user.update(user_params)
              format.html { redirect_to @user, notice: 'User was successfully updated.' }
              format.json { render :show, status: :ok, location: @user }
            else
              format.html { render :edit }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
          end
        end
      
    end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    search_params = params.permit(:search_term)
    @users = User.search(search_params)
    if @users.blank?
      redirect_to users_path, flash:{alert: "no successful search result"}
    else
      @users = @users.order('member_id desc').paginate(:page => params[:page], :per_page => 20)
      render :index
    end
    
  end

  def print_member_info

    # encoding: utf-8
    require 'barby'
    require 'barby/barcode/code_128'
    require 'barby/outputter/html_outputter'

    if params[:user_id]
    @a = params[:user_id]
    end  
    respond_to do |format|
      format.html
      format.pdf do
      render pdf: "print_member_info", :page_width => '16.54in', :page_height => '23.38in', :encoding => 'UTF-8' 
      end
    end
    
  end

  def reset_password
      @user = User.find(params[:user_id])
      params.permit(:user_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :ic, :phone, :email, :birthday, :member_id, :password, :user_type, :chinese_name, :line1, :line2, :line3, :postcode, :city, :state, :reset, :gender, :parent_name, :parent_ic, :parent_phone, :parent_email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show.html.erb
<div class="row">
      <div class="col-lg-4">
        <div class="panel panel-primary">
        <div class="panel-heading"><strong>Profile</strong></div>
          <div class="panel-body" style="color:black;">
            <p><strong>MemberID:</strong><br>
            <%= @user.member_id %></p>

            <p><strong>Name:</strong><br>
            <%= @user.name %></p>

            <p><strong>Chinese Name:</strong><br>
            <%= @user.chinese_name %></p>

            <p><strong>Email:</strong><br>
            <%if @user.email.empty? %>
            <p style="color: red;">Kindly update your email.</p>
            <% else %>
            <%= @user.email %></p>
            <% end %>

            <p><strong>Phone:</strong><br>
            <%= @user.phone %></p>

            <p><strong>Birthday:</strong><br>
            <%= @user.birthday.strftime('%d-%m-%y') %></p>

            <p><strong>Address:</strong><br>
            <%= @user.full_address %></p>

            <p><strong>Type:</strong>
            <%= @user.user_type %></p>  
            <div class="group" style="display: inline-flex;">
              <%= link_to 'View', user_path(@user), :class => 'btn btn-default' %>
              <% if current_user.is_admin? %>  
              <%= button_to 'Print Member Info', print_member_info_path(@user, :format => 'pdf'), :class => 'btn btn-default'  %>
              <% end %>
              
            </div>
          </div>
    </div>
  </div>
  <div class="col-lg-8">
    <% if @user.member_id == 'Pending'%>
    <div class="panel panel-primary">
      <div class="panel-body">
        <div class="well">
            You are required to visit the library and sign the guest book 4 times, make payment, and get the member card from the librarian.
        </div>
      </div>
    </div>
    <% else %>
    <div class="panel panel-primary">
    <div class="panel-heading"><strong>Loan Details</strong></div>
    <div class="panel-body" id="past">

          <% @loans.each do |loan| %>
           <div><center>
              <% if loan.book.image_url == nil or loan.book.image_url == ''%>
              <%= image_tag('shining-kids.jpg', width: '160')%>
              <% else %>             
              <%= image_tag(loan.book.image_url, width: '160')%>
              <% end %>               
              
              <br><p style="height: 50px"><strong><%= loan.book.name %></strong></p>
            
              <br>Loan: <strong><%= loan.loan_date.strftime('%d-%m-%y') %></strong>
              <br>Return: <strong><%= loan.return_date.strftime('%d-%m-%y') %></strong>
              <% if loan.is_extended == false %>
              <br><%= link_to 'Extend', return_date_extend_path(:id => loan.id), :class => 'btn btn-success' %>
              <% end %>  
              </center>
              </div>
           
          <%end %>
    </div>
      <div class="panel-heading"><strong>Reading History</strong> (<%= @user.loans.all.count%>)</div>
        <div class="panel-body" id="book-items">
        <% @loans_returned.each do |returned| %>
          <a href="<%=book_path(returned.book)%>">
                  <%= returned.book.name%>, <%= returned.book.barcode%>, <%= returned.actual_return_date%>
          </a>
          <% end %>
        </div>
    </div>
  </div>


  <% end %>
</div>

app/views/users/_user.html.erb
<%= user.name%>
<%= user.email%>

app/views/users/edit.html.erb
  <div class="row">
      <div class="col-lg-10">  
        <div class="panel panel-default">
          <div class="panel-heading"><h1>Editing User</h1></div>
            <div class="panel-body">


<%= render 'form', user: @user %>



            </div>
        </div>
      </div>
  </div>

app/views/users/index.html.erb
  <div class="row">
      <div class="col-lg-12">  
        <div class="panel panel-default">
          <div class="panel-heading">Members <small>Total</small> <span class="badge"><%= User.all.count%></span>
          <%= form_for User.new, :url => url_for(:controller => '/users', :action => 'search'), :method => 'get', html: { class: "form-group", style: "font-size:16px;"} do |f| %>
          <%= text_field_tag :search_term, params[:search_term], placeholder:"Member details" %>
          <%= f.submit 'Search', class: 'btn btn-default', id: 'submit' %>
          <% end %> 


          </div>
            <div class="panel-body">
              <table class="table" id="members">

                  <tr>
                    <col width="100">
                    <th>
                    <% if !params[:sort_by].nil? and params[:order]=="asc"%>
                    <%= link_to 'Member ID', users_path(:order => "desc", :sort_by => "member_id" ) %>
                      <% else %>
                    <%= link_to 'Member ID', users_path(:order => "asc", :sort_by => "member_id") %>
                      <% end %>
                    </th>
                    <th>
                    <% if !params[:sort_by].nil? and params[:order]=="asc"%>
                    <%= link_to 'Name', users_path(:order => "desc", :sort_by => "name" ) %>
                      <% else %>
                    <%= link_to 'Name', users_path(:order => "asc", :sort_by => "name") %>
                      <% end %>
                    </th>
                    <th>名字</th>
                    <th>IC</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Read Count</th>
                    <th></th>
                    <th></th>

                  </tr>



                  <% @users.each do |user| %>
                    <tr>
                    <% if user.member_id == nil %>
                    <td></td>
                    <%else%>
                    <td><%= user.member_id %></td>
                    <%end%>
                      <td><%= user.name %></td>
                      <td><%= user.chinese_name%></td>
                      <td><%= user.ic %></td>
                      <td><%= user.email %></td>
                      <td><%= user.phone %></td>
                      <td><%= user.read_count%></td>
                      <td><%= link_to 'Show', user , :class => 'btn btn-default' %></td>
                      <td><%= link_to 'Edit', edit_user_path(user) , :class => 'btn btn-default'%></td>

                    </tr>
                  <% end %>

              </table>
<div class="pagination_light"><%= will_paginate @books %></div>
              <br>
              <% if current_user.is_admin? %>
              <div class="container-fluid">
                <%= link_to 'New User', new_user_path, :class => 'btn btn-default'  %>
                </div>
              <% end %> 

            </div>
        </div>
      </div>
  </div>

app/views/users/new.html.erb
 <script type="text/javascript">
   var $user_type;

$(document).ready(function() {

$('#agree').click(function(){
$('div#registration-form').show()
$('div#library-rules').hide()
})

  $("select#user_user_type").change(function(){
     $user_type = $(this).val();
     console.log($user_type);
    if ($user_type == 'parents') {
      $('#my-kids').html('My Kad number')
      $('#parents-group').hide();
    };
        if ($user_type == 'children') {
      $('#my-kids').html('My Kid number')
      $('#parents-group').show();
    };

  });


});


 </script>
    <div class="row">
      <div class="col-lg-12" id="library-rules">
        <div class="panel panel-default">
          <div class="panel-body">
            申请会员须知图书馆规则
            <ol>
<li>欲借书者必须先申请成为会员（任何年龄层）。非会员可在馆内阅读但不可外借。</li>
<li>会员条件：沙登卫理公会会友（沙登卫理公会会友之两岁以下孩童免费申请）或莅临图书馆达四次之社区居民。</li>
<li>申请者必须填妥表格，连同终身会员费（RM50）交上。12岁以下申请者必须有家长或监护人同意。重做会员卡须缴交RM10。</li>
<li>申请者必须清楚也同意所有图书馆规则才签名，若孩童太小则需家长或监护人代签。</li>
<li>每张会员卡可借两本书或两片影音系列（CD/VCD/DVD）。</li>
<li>每片影音系列须缴费RM0.50。</li>
<li>归还期限为两个星期。迟还每本书或每片影音系列罚款数额为RM0.50/星期。</li>
<li>借出书籍或影音系列可重借一次。会员也可自行上网重借，也只限重借一次。</li>
<li>若所借的书损坏（掉进水，被画到图画不清，不见页数，重要页数被涂鸦。。。），图书馆有权要借书者以原价赔偿。</li>
<li>图书馆委员会评估其它损坏对书本整体的影响而作出处罚。如罚书本原价的10% 或20% 。</li>
<li>父母可进行亲子阅读，但不可大声玩闹，玩追逐游戏。</li>
<li>不可在图书馆内吃东西或喝饮料。</li>
<li>请保持馆内静态阅读空间的宁静与舒适感。</li>
            </ol>
            <div class="btn btn-primary" id="agree">Agree</div>
          </div>
        </div>
      </div>
      <div class="col-lg-12" style="display: none;" id="registration-form">  
        <div class="panel panel-default">
          <div class="panel-heading"><h1>New User</h1></div>
            <div class="panel-body" style="font-size:14px;">
<!-- form starts here -->

<div class="container-fluid">
<div class="col-lg-12">
<%= form_for(User.new, :html => {:class => 'form-horizontal'})  do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :user_type, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-2"> <%= f.select(:user_type, [['Children', 'children'],['Parents', 'parents']])%></div>
<% if !current_user.nil? and current_user.is_admin? %>


    <%= f.label :memberid, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-2"> <%= f.text_field :member_id, :value => 'Pending', :class => "form-control" %></div>

<% end %>
</div>
      <div class="form-group">
    <%= f.label :password, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-2"> <%= f.text_field :password, :value=>'123', :class => "form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-4"> <%= f.text_field :name, :class => "form-control" %></div>
    <%= f.label :chinese_name, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-2"> <%= f.text_field :chinese_name, :class => "form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label :birthday, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8"> <%= f.date_select :birthday, order: [:day, :month, :year], :start_year =>  Date.today.year - 50, :end_year => Date.today.year + 0 %></div>
  </div>
  <div class="form-group">
    <%= f.label :gender, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8"><%= f.select(:gender, [['Male', 'Male'],['Female', 'Female']] )%></div>
  </div>

  <div class="form-group">
    <%= f.label :email, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-4"> <%= f.text_field :email, :required => 'true', :class => "form-control" %></div>
    <%= f.label :phone, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-2"> <%= f.text_field :phone, :class => "form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label ('My Kid number'), :class => "col-lg-2 control-label", :id => 'my-kids', :style => 'text-transform: capitalize;'  %>
    <div class="col-lg-8"> <%= f.text_field :ic, :class => "form-control" %></div>
  </div>


  <div class="form-group">
    <%= f.label 'Address line 1', :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8"> <%= f.text_field :line1, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <%= f.label 'Address line 2', :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8"> <%= f.text_field :line2, :class => "form-control" %></div>
  </div>    
  <div class="form-group">
    <%= f.label :postcode, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8"> <%= f.text_field :postcode, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8"> <%= f.text_field :city, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8"> <%= f.text_field :state, :class => "form-control" %></div>
  </div>

<div id='parents-group'>
  
  <div class="form-group">
    <%= f.label :parent_name, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-3"> <%= f.text_field :parent_name, :class => "form-control" %></div>
    <%= f.label :parent_ic, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-3"> <%= f.text_field :parent_ic, :class => "form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label :parent_email, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-3"> <%= f.text_field :parent_email, :class => "form-control" %></div>
 
    <%= f.label :parent_phone, :class => "col-lg-2 control-label"  %>
    <div class="col-lg-3"> <%= f.text_field :parent_phone, :class => "form-control" %></div>
  </div>
</div>






  <div class="actions">
  <% if current_user.nil? %>
  <%= link_to ("Sign In"), sign_in_path, :class =>'btn btn-default' %>
  <% end %>
    <%= f.submit 'Submit', :class => "btn btn-default" %>
    <%= link_to 'Back', 'javascript:history.go(-1);', :class => 'btn btn-default' %>
    <%if @user.nil? %>
    <%= link_to 'Destroy',user_path(@user), data: {confirm: 'Are you sure?'} ,:method => :delete, :class => "btn btn-default"%>
    <%end %>
  </div>
<% end %>


</div>
</div>

<!-- form ends here -->


            </div>
        </div>
      </div>
  </div>

app/views/users/reset_password.html.erb
<div class="col-lg-8">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="well">
				Please key in your new password.
			</div>
				<%= form_for(@user, :html => {:class => 'form-horizontal'}) do |f| %>

				  <div class="form-group">
				    <%= f.label :password, :class => "col-lg-2 control-label"  %>
				    <div class="col-lg-8"> <%= f.text_field :password, :required => 'true', :class => "form-control" %></div>
				  </div>

				  <div class="form-group">
				    <%= f.label 'Retype Password', :class => "col-lg-2 control-label"  %>
				    <div class="col-lg-8"> <%= text_field_tag 'password', nil, :required => 'true', :class => "form-control" %></div>
				  </div>

				    <div class="actions">
				    <%= f.submit 'Submit', :class => "btn btn-default" %>
				    </div>

				 <% end %>
			
		</div>
	</div>
	
</div>

app/views/users/show.html.erb
<div class="row">
      <div class="col-lg-8">
        <div class="panel panel-default">
        <div class="panel-heading"><strong>Profile</strong></div>
          <div class="panel-body" style="color:black;">
            <p><strong>MemberID:</strong><br>
            <%= @user.member_id %></p>

            <p><strong>Name:</strong><br>
            <%= @user.name %></p>

            <p><strong>Chinese Name:</strong><br>
            <%= @user.chinese_name %></p>

            <p><strong>Email:</strong><br>
            <%if @user.email.empty? %>
            <p style="color: red;">Kindly update your email.</p>
            <% else %>
            <%= @user.email %></p>
            <% end %>
            <p><strong>Phone:</strong><br>
            <%= @user.phone %></p>

            <p><strong>Birthday:</strong><br>
            <%= @user.birthday.strftime('%d-%m-%y') %></p>

            <p><strong>Address:</strong><br>
            <%= @user.full_address %></p>

            <p><strong>Type:</strong>
            <%= @user.user_type %></p>  
            <div class="group" style="display: inline-flex;">
              <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-default' %>
              <% if !current_user.nil? and current_user.is_admin? %>  
              <%= button_to 'Print Member Info', print_member_info_path(@user, :format => 'pdf'), :class => 'btn btn-default'  %>
              <% end %>
              
          <%= link_to 'Back', root_path, :class => 'btn btn-default' %>
          <%= link_to 'Reset Password', reset_password_path(params[:id]), :class => 'btn btn-warning' %>
            </div>
          </div>
    </div>
  </div>



</div>