config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/set_new_password/:confirmation_token' => 'staticpages#set_new_password', as: 'set_new_password'
  post 'staticpages/public_password_submit' => 'staticpages#public_password_submit', as: 'public_password_submit'
  get 'staticpages/public_password_reset' => 'staticpages#public_password_reset', as: 'public_password_reset'
  get 'users/:user_id/reset_password' => 'users#reset_password', as: 'reset_password'

  resources :books do
    collection do
      get 'search'
      get 'quick_loan'
      get 'list_by_category'
    end
  end
  

  resource :session, controller: "clearance/sessions", only: [:create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  
  resources :users do
    collection do
      get 'search'
    end
  end

  post '/books/quick_create', to: 'books#quick_create', as: 'quick_create_book'

  resources :loans 
  resources :categories
  resources :publishers 
  
  match '/users/:user_id/print_member_info', to: "users#print_member_info", via: 'post', as: 'print_member_info'
  match '/history/loans', to: "loans#history", via: 'get', as: 'loan_history'
  match '/loans/search_book', to: "loans#search_book", via: 'post', as: 'search_book'
  match '/loans/:id/book_return', to: "loans#book_return", via: 'get', as: 'book_return'
  match '/loans/:id/return_date_extend', to: "loans#return_date_extend", via: 'get', as: 'return_date_extend'
  match '/search', to: "staticpages#search", via: 'post'
  match '/staticpages/print_book_barcodes', to: "staticpages#print_book_barcodes", via: 'post', as: 'print_barcode'
  match '/staticpages/print_book_barcodes', to: "staticpages#print_book_barcodes", via: 'get'
  match '/staticpages/print_member_cards', to: "staticpages#print_member_cards", via: 'post', as: 'print_member'
  match '/staticpages/print_member_cards', to: "staticpages#print_member_cards", via: 'get'
  match '/staticpages/import_books', to: "staticpages#import_books", via: 'post', as: 'import_books'  
  match '/staticpages/import_members', to: "staticpages#import_members", via: 'post', as: 'import_members' 
  match '/staticpages/training', to: "staticpages#training", via: 'get', as: 'training' 
  root 'staticpages#home'

  get 'staticpages/help' => 'staticpages#help', as: 'help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord
	belongs_to :book
	belongs_to :user
	
	before_create :book_physically_available
	after_create :delete_empty, :assign_dates, :record_history
	validates :user, presence: true


	# calculate how much fine based on working weeks, 
	# need to find out which week was the book returned date. 
	# if 1/14 is the 2nd week, checks todays date is in which week
	# get the difference of the week and calculate the fine.
	def estimate_fine
		cur_week = Time.now.strftime("%U").to_i
		return_week = self.return_date.strftime("%U").to_i
		late = cur_week - return_week
		if late > 0
		fine = late * 0.50
		else
		fine = 0.00
		end
		fine
	end


	def book_physically_available
		if self.book == nil
			self.errors.messages[:has_returned] = "This book isn't returned yet."
		end
		
	end

	def return_date_extend
		if self.is_extended == false
		a = self.return_date
		self.update(return_date: a+14 , is_extended: true)
		else
			# errors.add(:is_extended, "This loan already extended") 
			self.errors.messages[:is_extended] = "This loan is extended."
		end
	end

	def book_return
		if self.has_returned == false
			self.update(has_returned: true, actual_return_date: Time.zone.today, fine_amount: self.estimate_fine)
		end
	end

	def returned?
		self.has_returned == true
	end

	def assign_dates
		if self.return_date == nil
	  a = Time.zone.today
		self.update(loan_date: a, return_date: a+14) 
		end
	end
	
	private

	def delete_empty
		if self.book_id == nil or self.user_id == nil
		self.destroy
		end
	end


end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy, :return_date_extend, :book_return]

  # GET /loans
  # GET /loans.json
  def index
    
    if current_user == nil
      require_login
    elsif current_user.is_admin?
      @loans = Loan.all.where(has_returned: false).order('return_date ASC')
    elsif !current_user.is_admin?
      @loans = Loan.where(user_id: current_user.id)
    end
    
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
        a = Time.zone.today
    @loan = Loan.new(loan_date: a, return_date: a+7)
    user = User.find_by(member_id: params[:user])
    if user.nil?
    else
    @loans = user.loans.where(has_returned: false).order('return_date ASC')
    end
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    respond_to do |format|
      if @loan.save
        format.html { redirect_to new_loan_path(:user => @loan.user.member_id) , notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { redirect_to books_path, alert: @loan.errors.full_messages.join }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  def return_date_extend

    @loan.return_date_extend
    if current_user.is_admin?
      if @loan.errors.messages.first.nil?
        @message = "Loan extension was succcessful."
       respond_to do |format|
        format.html { redirect_to loans_path, notice: @message }
        format.json { head :no_content }
        end
      else
        @message = @loan.errors.messages.first[1]
       respond_to do |format|
        format.html { redirect_to loans_path, alert: @message }
        format.json { head :no_content }
        end
      end 
    else
      if @loan.errors.messages.first.nil?
        @message = "Loan extension was succcessful."
       respond_to do |format|
        format.html { redirect_to root_path, notice: @message }
        format.json { head :no_content }
        end
      else
        @message = @loan.errors.messages.first[1]
       respond_to do |format|
        format.html { redirect_to root_path, alert: @message }
        format.json { head :no_content }
        end
      end   
    end
  end


  def book_return

    @loan.book_return

    if @loan.errors.messages.first.nil?
      @message = "Return was succcessful."
     respond_to do |format|
      format.html { redirect_to new_loan_path(user: @loan.user.member_id), notice: @message }
      format.json { head :no_content }
    end
    else
      @message = @loan.errors.messages.first[1]
     respond_to do |format|
      format.html { redirect_to loans_path, alert: @message }
      format.json { head :no_content }
    end
    end
    
  end

  def history
    if current_user == nil
      require_login
    elsif current_user.is_admin?
      @loans = Loan.all.where(has_returned: true).order('loan_date DESC')
    end
  end

  def search_book
      @user = User.find_by(member_id: params[:user])
      @book = Book.super_search(params).first
    respond_to do |format|
      format.html { render 'new' }
      format.js
    end  

  end



  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list throu gh.
    def loan_params
      params.require(:loan).permit(:loan_date, :return_date, :book_id, :user_id, :user)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
      <%= form_for(Loan.new) do |f| %>
        

        <div class="field" id="book_loan">
          <%= f.label :book_id %>
          <% if @book.loans.empty? %>
            <%= f.hidden_field :book_id, :value => Book.find(@book.id).id %>
            <%= Book.find(@book.id).name %>, <%= Book.find(@book.id).barcode %>, <%= Book.find(@book.id).isbn %>              
          <% elsif !@book.loans.last.returned? %>
            <p style="color: red;"><%= Book.find(@book).name%> has been loaned.</p>
          <% else %>
            <%= f.hidden_field :book_id, :value => Book.find(@book.id).id %>
            <%= Book.find(@book.id).name %>
          <% end %>
        </div>
        <br>
            <div class="field">
              
              <% if  !User.find_by(member_id: params[:user]).nil? %>
                <h1><%= User.find_by(member_id: params[:user]).chinese_name %> <small><%= User.find_by(member_id: params[:user]).name %></small></h1> <%= User.find_by(member_id: params[:user]).member_id %>
                <%= f.hidden_field :user_id, :value => User.find_by(member_id: params[:user]).id %>
              <% else %>
                <p>No User Found</p>
              <% end %>
            </div>
            <br>
            <br>
        <div class="field">
          <%= f.label :loan_date %>
          <%= f.date_select :loan_date %>
        </div>

        <div class="field">
          <%= f.label :return_date %>
          <%= f.date_select :return_date, selected: 14.days.from_now %>
        </div>


        <div class="actions">
        <% if @book.loans.empty? %>
        <%= f.submit 'Create loan', :class => 'btn btn-default' %>
        <% elsif @book.loans.last.returned? %>
          <%= f.submit 'Create loan', :class => 'btn btn-default' %>
        <% end %>
        </div>
      <% end %>

app/views/loans/_loan.html.erb
<% if loan.estimate_fine == 0 %>
  <tr>
    <td><%= loan.loan_date.strftime('%d-%m-%y') %></td>
    <td><%= loan.return_date.strftime('%d-%m-%y') %></td>
    <td><%= loan.book.name %></td>
    <td><%= link_to loan.user.name, user_path(loan.user)%></td> 
    <% if current_user.is_admin? %>
      <td><%= link_to 'Edit', edit_loan_path(loan), :class => 'btn btn-default' %></td>
      <td>
        <% if loan.has_returned == false%>
        <%= link_to 'Return', book_return_path(:id => loan.id), :class => 'btn btn-success' %>
        <% end %>

        <% if loan.is_extended == false%>
        <%= link_to 'Extend', return_date_extend_path(:id => loan.id), :class => 'btn btn-primary' %>
        <% end %>
      </td>
      <td>RM <span id="fines"><%= ('%.2f' % loan.estimate_fine) %></span></td>

    <% end %>
  </tr>
<% else %>
  <tr style="color:red;">
    <td><%= loan.loan_date.strftime('%d-%m-%y') %></td>
    <td><%= loan.return_date.strftime('%d-%m-%y') %></td>
    <td><%= loan.book.name %></td>
    <td><%= link_to loan.user.name, user_path(loan.user)%></td> 
    <% if current_user.is_admin? %>
      <td><%= link_to 'Edit', edit_loan_path(loan), :class => 'btn btn-default' %></td>
      <td>
        <% if loan.has_returned == false%>
        <%= link_to 'Return', book_return_path(:id => loan.id), :class => 'btn btn-success' %>
        <% end %>

        <% if loan.is_extended == false%>
        <%= link_to 'Extend', return_date_extend_path(:id => loan.id), :class => 'btn btn-primary' %>
        <% end %>
      </td>
      <td>RM <span id="fines"><%= ('%.2f' % loan.estimate_fine) %></span></td>

    <% end %>
  </tr>
<% end %>

app/views/loans/_search_book.html.erb
<%= form_tag('/loans/search_book', remote: true) do -%>
<%= text_field_tag :book, params[:barcode], placeholder: 'ISBN or barcode', :onkeyup => 'countChar(this)', :autocomplete => 'off' %>
<%= hidden_field_tag :user, params[:user] %>
<%= submit_tag 'Search', :id => 'search' %>
<% end -%>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

          <%= form_for @loan do |f| %>
            
            <div class="field" id="book_loan">
              <%= f.label :book_id %>
              <% if @loan.book == nil %>
                  <p>No Book Found</p>
              <% else %>

              <%= f.hidden_field :book_id, :value => @loan.book.id %>
              <%= @loan.book.name %>
              <% end %>
            </div>

            <div class="field">
              <%= f.label :user_id %>
              <% if  !@loan.user.nil? %>
                <%= @loan.user.name %>,  <%= @loan.user.member_id %>
                <%= f.hidden_field :user_id, :value => @loan.user.id %>
              <% else %>
                <p>No User Found</p>
              <% end %>
            </div>

            <div class="field">
              <%= f.label :loan_date %>
              <%= f.date_select :loan_date, order: [:day, :month, :year] %>
            </div>

            <div class="field">
              <%= f.label :return_date %>
              <%= f.date_select :return_date, selected: 14.days.from_now, order: [:day, :month, :year] %>
            </div>


            <div class="actions">
              <%= f.submit 'Submit', :class => 'btn btn-default' %>
            </div>
          <% end %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/history.html.erb
<div class="row">
  <div class="col-lg-9">
    <div class="panel panel-default">
    <div class="panel-heading" style="font-size:30px;">Loans history</div>
      <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Loan date</th>
            <th>Return date</th>
            <th>Actual return date</th>
            <th>Fined</th>
            <th>Book</th>
            <th>User</th>



          </tr>
        </thead>

        <tbody>
          <% @loans.each do |loan| %>
            <tr>
              <td><%= loan.loan_date.strftime('%d-%m-%y') %></td>
              <td><%= loan.return_date.strftime('%d-%m-%y') %></td>
              <td><%= loan.actual_return_date.strftime('%d-%m-%y') %></td>
              <td>RM <%= ('%.2f' % loan.fine_amount) %></td>
              <td><%= loan.book.name %></td>
              <td><%= loan.user.name %></td>




            </tr>
          <% end %>
        </tbody>
      </table>
<%= link_to 'Back', 'javascript:history.go(-1);', :class => 'btn btn-default' %>
      <br>

      </div>
    </div>
  </div> 
  <div class="col-lg-3">
<b>Read count</b>
<% Loan.group(:user_id).count.sort_by{|x,y| y}.reverse.each do |x,y| %>
<div><%= link_to User.find(x).chinese_name, user_path(User.find(x))%>, <%= y%></div>
<% end %>   
  </div>
</div>

app/views/loans/index.html.erb
<div class="row">
  <div class="col-lg-9">
    <div class="panel panel-default">
    <div class="panel-heading" style="font-size:30px;">Loans</div>
      <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Loan date</th>
            <th>Return date</th>
            <th>Book</th>
            <th>User</th>
            <th colspan="2"></th>
            <th>Estimate fine</th>

          </tr>
        </thead>

        <tbody>
                <%= render @loans %>
 

        </tbody>
      </table>


      <br>
<%= link_to 'History', loan_history_path, :class => 'btn btn-default'%>
<%= link_to 'Training', training_path, :class => 'btn btn-default'%>
      </div>
    </div>
  </div>  
  <div class="col-lg-3">
<b>Read count</b>
<% Loan.group(:user_id).count.sort_by{|x,y| y}.reverse.each do |x,y| %>
<div><%= link_to User.find(x).chinese_name, user_path(User.find(x))%>, <%= y%></div>
<% end %>  
  </div>
</div>

app/views/loans/new.html.erb
<div class="col-lg-5">
	<div class="panel panel-default">
		<div class="panel-heading" style="font-size:30px;">Loans</div>
		<div class="panel-body">
			  <%= render 'search_book'%>
			  <div id="loan_form">
		      <%= form_for(Loan.new) do |f| %>
		        

		        <div class="field" id="book_loan">
		          <%= f.label :book_id %>
		          <% if @book == nil %>
		              <p>No Book Found</p>
		          <% else %>

		          <%= f.hidden_field :book_id, :value => Book.find(@book).id %>
		          <%= Book.find(@book).name %>
		          <% end %>
		        </div>
		        <br>
		        <div class="field">
		          
		          <% if  !User.find_by(member_id: params[:user]).nil? %>
		            <h1><%= User.find_by(member_id: params[:user]).chinese_name %> <small><%= User.find_by(member_id: params[:user]).name %></small></h1> <%= User.find_by(member_id: params[:user]).member_id %>
		            <%= f.hidden_field :user_id, :value => User.find_by(member_id: params[:user]).id %>
		          <% else %>
		            <p>No User Found</p>
		          <% end %>
		        </div>
		        <br>
		        <br>
		        <div class="field">
		          <%= f.label :loan_date %>
		          <%= f.date_select :loan_date, order: [:day, :month, :year] %>
		        </div>

		        <div class="field">
		          <%= f.label :return_date %>
		          <%= f.date_select :return_date, selected: 14.days.from_now, order: [:day, :month, :year] %>
		        </div>


		        <div class="actions">
		          <%= f.submit 'Create loan', :class => 'btn btn-default' %>
		        </div>
		      <% end %>
			  </div>

		</div>
		
	</div>


	<%= link_to 'Back', loans_path %>
	
</div>
<div class="col-lg-7">

    <div class="panel panel-default">
    <div class="panel-heading" style="font-size:30px;">Returns</div>
      <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
          <col width="10%" />
          <col width="10%" />
          <col width="20%" />
          <col width="10%" />
          <col width="10%" />
          <col width="10%" />
          <col width="10%" />
          <col width="5%" />
            <th>Loan date</th>
            <th>Return date</th>
            <th>Book</th>
            <th>Barcode</th>
            <th>User</th>
            <th colspan="2"></th>
            <th>Estimate fine</th>

          </tr>
        </thead>

        <tbody>
        <% if !@loans.nil? %>
          <% @loans.each do |loan| %>
            <tr>
              <td><%= loan.loan_date.strftime('%d-%m-%y') %></td>
              <td><%= loan.return_date.strftime('%d-%m-%y') %></td>
              <td><%= loan.book.name %></td>
              <td><%= loan.book.barcode %></td>
              <td><%= link_to loan.user.name, user_path(loan.user)%></td> 
              <% if current_user.is_admin? %>
              <td><%= link_to 'Edit', edit_loan_path(loan), :class => 'btn btn-default' %></td>
              <td>
              <% if loan.has_returned == false%>
              <%= link_to 'Return', book_return_path(:id => loan.id), :class => 'btn btn-success' %>
              <% end %>
              </td>
              <td>RM <%= ('%.2f' % loan.estimate_fine) %></td>

              <% end %>
            </tr>
          <% end %>
        <% end %>  
        </tbody>
      </table>

      </div>
    </div>

</div>

app/views/loans/search_book.js.erb
 $("#loan_form").html("<%= j(render 'form', user: @user, book: @book) %>"); 
 $( "#book" ).focus();
  $( "#book" ).val('');

app/views/loans/show.html.erb
	<div class="row">
		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-body">
				
				  <strong>Loan date:</strong>
				  <%= @loan.loan_date %><br>
				

				
				  <strong>Return date:</strong>
				  <%= @loan.return_date %><br>
				

				
				  <strong>Book:</strong>
				  <%= @loan.book_id %><br>
				
				  <strong>User:</strong>
				  <%= @loan.user_id %><br>
				

				<%= link_to 'Edit', edit_loan_path(@loan) %> |
				<%= link_to 'Back', loans_path %>
				</div>
		</div>	
	</div>
</div>

app/views/loans/top_reader.html.erb
<h1>Loans#top_reader</h1>
<p>Find me in app/views/loans/top_reader.html.erb</p>