config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/set_new_password/:confirmation_token' => 'staticpages#set_new_password', as: 'set_new_password'
  post 'staticpages/public_password_submit' => 'staticpages#public_password_submit', as: 'public_password_submit'
  get 'staticpages/public_password_reset' => 'staticpages#public_password_reset', as: 'public_password_reset'
  get 'users/:user_id/reset_password' => 'users#reset_password', as: 'reset_password'

  resources :books do
    collection do
      get 'search'
      get 'quick_loan'
      get 'list_by_category'
    end
  end
  

  resource :session, controller: "clearance/sessions", only: [:create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  
  resources :users do
    collection do
      get 'search'
    end
  end

  post '/books/quick_create', to: 'books#quick_create', as: 'quick_create_book'

  resources :loans 
  resources :categories
  resources :publishers 
  
  match '/users/:user_id/print_member_info', to: "users#print_member_info", via: 'post', as: 'print_member_info'
  match '/history/loans', to: "loans#history", via: 'get', as: 'loan_history'
  match '/loans/search_book', to: "loans#search_book", via: 'post', as: 'search_book'
  match '/loans/:id/book_return', to: "loans#book_return", via: 'get', as: 'book_return'
  match '/loans/:id/return_date_extend', to: "loans#return_date_extend", via: 'get', as: 'return_date_extend'
  match '/search', to: "staticpages#search", via: 'post'
  match '/staticpages/print_book_barcodes', to: "staticpages#print_book_barcodes", via: 'post', as: 'print_barcode'
  match '/staticpages/print_book_barcodes', to: "staticpages#print_book_barcodes", via: 'get'
  match '/staticpages/print_member_cards', to: "staticpages#print_member_cards", via: 'post', as: 'print_member'
  match '/staticpages/print_member_cards', to: "staticpages#print_member_cards", via: 'get'
  match '/staticpages/import_books', to: "staticpages#import_books", via: 'post', as: 'import_books'  
  match '/staticpages/import_members', to: "staticpages#import_members", via: 'post', as: 'import_members' 
  match '/staticpages/training', to: "staticpages#training", via: 'get', as: 'training' 
  root 'staticpages#home'

  get 'staticpages/help' => 'staticpages#help', as: 'help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KidsLibrary</title>
    <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path%>"><%= t('my_library')%></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <% if !current_user.nil? and current_user.is_admin? %>
          <li> <%= link_to "Members", users_url, :class => "btn btn-default" %></li>
          <li> <%= link_to "Loaned List", loans_url, :class => "btn btn-default" %></li>  
          <li> <%= link_to "Tools", '/staticpages/help', :class => "btn btn-default" %></li>
          <li>
          <%= form_for Loan.new , :url => url_for(:controller => '/loans', :action => 'new') , :method => 'get', html: { class: "navbar-form navbar-left"} do |f| %>
          <%= text_field_tag :user, params[:user], :required => 'true', placeholder: "Member ID", :onkeyup => 'countMemberId(this)' %>
          <%= f.submit 'Loan/Return', class: 'btn btn-warning', id: 'submit' %>
          <% end %>         
          </li>
        <% end %> 
        
      </ul>
      
      <ul class="nav navbar-nav navbar-left">

       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> <%= t('books')%> 
          <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><%= link_to '绘本 Picture Books', :action => 'list_by_category', :controller => '/books', :category => '1' %></li>
            <li><%= link_to '英文书 English Books', :action => 'list_by_category', :controller => '/books', :category => '2' %></li>
            <li><%= link_to '教导书籍 Teaching Books', :action => 'list_by_category', :controller => '/books', :category => '3' %></li>
            <li><%= link_to '信仰书籍 Religion Books', :action => 'list_by_category', :controller => '/books', :category => '4' %></li>
            <li><%= link_to '其他 Other Books', :action => 'list_by_category', :controller => '/books', :category => '5' %></li>
            <li><%= link_to '多媒体 Multimedia', :action => 'list_by_category', :controller => '/books', :category => Category.find_by(name:'Multimedia').id %></li>
            </ul>
       </li>
       <li>
          <%= form_for Book.new, :url => url_for(:controller => '/books', :action => 'search'), :method => 'get', html: { class: "navbar-form navbar-left"} do |f| %>
          <%= text_field_tag :book_name, params[:book_name], placeholder:"Book name" %>
          <%= text_field_tag :author, params[:author], placeholder:"Author name" %>        
          <%= text_field_tag :barcode, params[:barcode], placeholder:"Barcode" %> 
            <%= button_tag(type: "submit", class: "btn btn-primary", id: 'submit') do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
            <% end %>
          <% end %>
       </li>
       <% if signed_in? %>
          <li>
          <a href="<%= user_path(current_user)%>"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= current_user.chinese_name %></a></li>
          <li><%= link_to "Sign out", sign_out_path, method: :delete, :class => 'btn btn-default' %></li>
          <% else %>
          <li><%= link_to "Sign in", sign_in_path, :class => 'btn btn-default'%></li>
       <% end %>
      </ul>

      </div>
  </div>
</nav>
  <body>
    <%= image_tag('background.jpg', :class => "background")%>
    <div class="container">
    <center>
      <script type="text/javascript">
        $("#flash").delay(10000).fadeOut('slow');
      </script>
      <div id="flash" style="width: 70%; margin-right: auto; margin-left: auto;">
        <% flash.each do |key, value| %>
            <% if key = notice %>
              <div class="alert alert-success" role="alert"><div class="flash <%= key %>"><%= value %></div></div>
            <% elsif key = alert %>
              <div class="alert alert-danger" role="alert"><div class="flash <%= key %>"><%= value %></div></div>
            <%end %>
        <% end %>
      </div>
    </center>
    </div>
    <div class="container-fluid" id="homepage" >
    <%= yield %>
    </div>
    <footer class="footer">
      <div class="container-fluid" style="padding:20px; color:black;">
        <div class="row">
          <div class="col-lg-4">
            <h2>图书馆开放时间：</h2>
              <div>星期六: 10am - 1pm & 2pm -5pm</div>
              <div>星期日: 10am - 10.30am & 12pm - 1pm</div>
              <div>公共假期休息</div>
          </div>
          <div class="col-lg-4">
            <h2>亮亮亲子共读会：</h2>
            <div>每个月第三个星期六</div>
            <div>0-4岁 10:30am-11:30am</div>
<div>5-12岁 11:30am-12:30noon</div>
          </div>
          <div class="col-lg-4">
          <h2>地址：</h2>
            <div>20A, JLN PSK8, </div>
            <div>PUSAT PERDAGANGAN SERI KEMBANGAN, </div>
            <div>43300 S.K. </div>
          </div>
        </div>
      </div>


     </footer>
    <script type="text/javascript">
document.getElementById('book').onkeydown = function(e) {
e = e || window.event;
//alert(e.keyCode);
switch( e.keyCode || e.which) {
case 37:
case 36:

if(e.altKey) {
return false;
}
}
}

$(function() {
$('#book').keydown(function(objEvent) {

if (objEvent.keyCode == 9 || objEvent.keyCode == 13) {
objEvent.preventDefault();
}

});
});

      function countChar(val) {
      var len = val.value.length;
        if (len >= 13) {
          $("#search").focus();
          $("#search").click();
        } else {
          $('#charNum').text(len);
        }
      }

      function countMemberId(val) {
      var len = val.value.length;
      if (len >= 10) {
          $("#book").focus();
          $("#submit").focus();
          $("#submit").click();
        } else {
          $('#charNum').text(len);
        }
      }
    </script>
  </body>
</html>